version: "3"

services:
  mosquitto:
    image: eclipse-mosquitto
    volumes:
      - ./config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./config/passwds:/etc/mosquitto/password_file
    ports:
      - "1883:1883"
      - "9001:9001"
